# Changes here will be overwritten by Copier
_commit: 3249a90
_src_path: gh:mochic/copier-pdm-npc
add_requirements_txt: false
author_email: ben.hardcastle@alleninstitue.org
author_fullname: Ben Hardcastle
author_username: bjhardcastle
build_doc: true
copyright_date: '2024'
copyright_holder: ''
copyright_holder_email: ''
copyright_license: MIT
package_version: 0.1.0
project_description: ''
project_name: mochic7b1937c0
python_package_distribution_name: mochic7b1937c0
python_package_import_name: mochic7b1937c0
python_package_requires_python: '>=3.9'
repository_name: mochic7b1937c0
repository_namespace: ''

